import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowUpRight, BookOpen, Download, Expand, FileText, Users, X } from 'lucide-react';
import type { ResearchPaper } from '../../types';
import papersData from '../data/papersData.json';

const papers = papersData as ResearchPaper[];
const ease = [0.22, 1, 0.36, 1] as const;

export default function PapersPage() {
  const [selected, setSelected] = useState<ResearchPaper>(papers[0]);
  const [readerOpen, setReaderOpen] = useState(false);
  const selectPaper = (paper: ResearchPaper) => { setSelected(paper); if (window.innerWidth < 1024) setReaderOpen(true); };
  return <main className="papers-page"><nav className="papers-nav"><a href="/"><ArrowLeft size={16} /> Portfolio</a><span>Research archive / 2026</span></nav>
    <section className="papers-hero"><motion.div initial={{ opacity:0,y:22 }} animate={{ opacity:1,y:0 }} transition={{ duration:.7,ease }}><p className="eyebrow">Research archive</p><h1>Notes from the<br /><em>edge of learning.</em></h1><p>Experiments, papers, and systems exploring how intelligent agents can reason, collaborate, and create with care.</p></motion.div><motion.div initial={{ opacity:0,scale:.94 }} animate={{ opacity:1,scale:1 }} transition={{ duration:.7,delay:.12,ease }} className="papers-orbital"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="orbit-core">RL<br />×<br />MARL</div><span>RESEARCH<br />IN MOTION</span></motion.div></section>
    <section className="papers-content"><div className="papers-list"><div className="papers-list-heading"><p className="eyebrow">Selected papers</p><span>{String(papers.length).padStart(2, '0')} records</span></div>{papers.map((paper, index) => <motion.article key={paper.title} initial={{ opacity:0,y:20 }} whileInView={{ opacity:1,y:0 }} viewport={{ once:true }} transition={{ duration:.5,delay:index*.08 }} className={`paper-card ${selected.title === paper.title ? 'is-selected' : ''}`} onClick={() => selectPaper(paper)}><div className="paper-number">0{index + 1}</div><div className="paper-main"><p>{paper.venue} · {paper.year}</p><h2>{paper.title}</h2><p className="paper-summary">{paper.summary}</p><div className="paper-meta"><span><Users size={14} /> {paper.collaborators.length} {paper.collaborators.length === 1 ? 'author' : 'authors'}</span><span className="paper-status">{paper.status}</span></div></div><button aria-label={`Open ${paper.title}`}><ArrowUpRight size={20} /></button></motion.article>)}</div>
      <aside className="paper-reader"><div className="reader-title"><div><p className="eyebrow">Currently reading</p><h2>{selected.title}</h2></div><button onClick={() => setReaderOpen(true)} aria-label="Expand reader"><Expand size={18} /></button></div><div className="reader-frame">{selected.pdfPath ? <iframe title={selected.title} src={`${selected.pdfPath}#toolbar=0&navpanes=0&view=FitH`} /> : <div><FileText size={34} />No document available</div>}</div><div className="reader-actions"><a href={selected.pdfPath} target="_blank" rel="noreferrer"><Download size={15} /> Download PDF</a><button onClick={() => setReaderOpen(true)}>Read full paper <ArrowUpRight size={15} /></button></div></aside></section>
    <section className="papers-manifesto"><p>“Agents that debate are smarter than agents that agree.”</p><span>— Shivam Prasad</span><div><BookOpen size={18} /> Every paper begins with a question worth staying with.</div></section>
    <AnimatePresence>{readerOpen && <motion.div className="paper-overlay" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}><button className="paper-backdrop" onClick={() => setReaderOpen(false)} aria-label="Close paper reader" /><motion.section className="paper-overlay-reader" initial={{ opacity:0,y:25,scale:.98 }} animate={{ opacity:1,y:0,scale:1 }} exit={{ opacity:0,y:20,scale:.98 }} transition={{ duration:.35,ease }}><header><div><p className="eyebrow">Paper reader</p><h2>{selected.title}</h2></div><div><a href={selected.pdfPath} target="_blank" rel="noreferrer"><Download size={15} /> Download</a><button onClick={() => setReaderOpen(false)}><X size={18} /> Close</button></div></header><iframe title={`${selected.title} reader`} src={`${selected.pdfPath}#toolbar=1&navpanes=0&view=FitH`} /></motion.section></motion.div>}</AnimatePresence>
  </main>;
}
